topicsList = (
    ' Who is your favorite male anime character?', ' Who is your favorite female character?',
    ' What is your favorite anime soundtrack?', 'What is your favorite anime opening + animation?',
    'What is your favorite anime ending song + animation?', 'What is your favorite anime scene?',
    'If you could meet an anime character who would it be?', 'What anime character is most similar to you in terms of personality?',
    'What is your favorite thing about anime?', 'What is your least favorite thing about anime?',
    ' Who are your favorite anime couple?', ' Who is your favorite anime animal?',
    'What anime would make a good game?', 'What game would make a good anime?',
    'What was the first anime you ever watched?', 'Do you think you’ll ever stop watching anime?',
    'What is your favorite genre of anime?', 'What is your least favorite genre of anime?',
    'Are you open about watching anime with people you know?', 'Have you ever been to Japan?',
    'What anime was the biggest let down for you?', 'What anime was better then expected?',
    'What is the best anime fight scene?', 'Who is your anime waifu?',
    'What was your favorite video game as a child?', ' Most embarrassing moment?',
    'Can you drive?', 'Do you own a car?',
    'Are you mature?', ' What year were you born?',
    'Do you prefer cats or dogs?', 'Describe yourself physically.',
    'What would you name your first child?', 'What is the worst injury you have ever had?',
    'What is your worse habit?', 'Do you drink or smoke?',
    'Do you have a tattoo?', 'Are you a morning person or a night person?',
    'Have you ever slept past midday?', 'Do you regret anything?',
    'Can you count the number of friends you have on one hand?',
    ' Do you wear glasses?', 'Are you a picky eater?',
    ' Would you die for someone?', 'If you could have any superpower, what would it be?',
    'Do you believe in the supernatural?', 'Would you rather be rich or famous?',
    'Have you ever committed a crime?', 'Pirates or ninjas? Time traveler or ghost?',
    'Does someone have a crush on you?', 'Are you in a relationship?',
    'Do you believe in God or a higher being?', 'What do you do in your free time?',
    'Do you play any musical instruments?', 'Do you draw, paint or do art?',
    'Do you like dancing?', 'What do you do/study?',
    'What is your most (or least) favorite subject in school?', 'How do you get along with the people you work with?',
    'Do you love working there or are you doing it for the money?', 'What is your dream job?',
    'What countries have you traveled to? ', 'What was your biggest experience of “culture shock” in another country?',
    'Where in the world would you love to live most? Why?', 'How does your home country compare to here?',
    'What’s the worst thing that’s happened to you while traveling?', 'Have you ever traveled by yourself?',
    'Do you speak any other languages?', 'What’s your favorite movie (or TV show) ever?',
    'Which movie/book/show are you ashamed to admit you love?', 'Which movie are you most looking forward to being released?',
    'What kind of books do you usually read?', 'What kind of music are you into right now?',
    'What concerts have you been to?', 'What movies have you watched more than once? ',
    'Do you play video games?'
)
